### ISSUE TITLE
Error while ionic production build

### ISSUE THREAD

**Issue by veerajongit** [eakoriakin/ionic-select-searchable-demo#13]
$ ionic cordova run android --prod --aot

Error: Metadata version mismatch for module node_modules/ionic-select-searchable/ionic-select-searchable.d.ts, found version 4, expected 3

**Comment by eakoriakin** [comment]
Hi, try to import `SelectSearchableModule` to every module where `SelectSearchable is used`.
https://github.com/eakoriakin/ionic-select-searchable/issues/12#issuecomment-382639265

**Comment by eakoriakin** [comment]
Closed as duplicate of https://github.com/eakoriakin/ionic-select-searchable/issues/3.
