### ISSUE TITLE
Failed to take production build

### ISSUE THREAD

**Issue by ashavyshakh** [eakoriakin/ionic-select-searchable-demo#14]
Hi,
I ve tried 2 solutions , 

> 1.0.14 version used

> tried to import SelectSearchableModule to every module where SelectSearchable is used
( eg:  import { SelectSearchableModule } from 'ionic-select-searchable';
)
error:Error: Metadata version mismatch for module node_modules/ionic-select-searchable/ionic-select-searchable.d.ts, found version 4, expected 3
But none of them worked.any idea ? Please help

**Comment by eakoriakin** [comment]
Hey, can you try the latest version?

**Comment by ashavyshakh** [comment]
I tried the following
`npm i ionic-select-searchable@latest`
then I got version 1.1.2 in my package.json
But i got the same error :(

**Comment by eakoriakin** [comment]
@ashavyshakh can you create a small GutHub repo that I could clone to reproduce the error?

**Comment by eakoriakin** [comment]
Closed for inactivity.
