### ISSUE TITLE
not working on a modal.

### ISSUE THREAD

**Issue by akshaySMahendrakar** [eakoriakin/ionic-select-searchable-demo#18]
hey i have difficulties loading select-searchable. my parent page is  a modal and in modal i have given select-searchable modal. so the code is not working on modal

**Comment by eakoriakin** [comment]
Hey, it should work. Make sure that you are using the latest version of `ionic-select-searchable`.
Have a look at this demo:
https://ionic-select-searchable-inside-modal.stackblitz.io/
