### ISSUE TITLE
Can't bind to 'multiple' since it isn't a known property of 'select-searchable'. 

### ISSUE THREAD

**Issue by jessicastorm1986** [eakoriakin/ionic-select-searchable-demo#20]
Errors coming: [using IONIC 3]

 1. If 'select-searchable' is an Angular component and it has 'multiple' input, then verify that it is part of this module. 
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the'@NgModule.schemas' of this component. (" itemTextField="USR" [canSearch]="true" [ERROR ->][multiple]="true" (onChange)="portChangef(value,i)"> </select-searchable>")

I have imported this in my `app.module.ts`
`import { SelectSearchableModule } from 'ionic-select-searchable';`

```
 imports: [
  SelectSearchableModule,
    BrowserModule,
    IonicModule.forRoot(MyApp),
    SuperTabsModule.forRoot(),
```

Still i am gettting this error while i try to build.
Please help.

**Comment by eakoriakin** [comment]
Hey, use a new name - [isMultiple](https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation#ismultiple).
