### ISSUE TITLE
Unable to bind value to select-searchable via [(ngModel)]

### ISSUE THREAD

**Issue by coolvasanth** [eakoriakin/ionic-select-searchable-demo#22]
Hi, thank u @eakoriakin for the great plugin it is very useful. But I'm facing a small issue with it. In my case some values has to be prefed to the search bar when user enters the page.  (Ex: Default country has to be selected, before choosing a country of user choice). I tried setting the particular ID of a JSON array to set the value, but it is not working. Can u please help me out with an example ?

**Comment by coolvasanth** [comment]
Hi, I found answer to this by myself. I faced issue in binding a single value to the select-searchable. When I bind it with the object it was working fine. 
Ex: If below is the pattern of the array which will be providing values to select-searchable,

`[{id:1, country: USA},{id:2, country: UK},{id:3, country: Germany}] `

Then to fill a value to the select-searchable set [{ngmodel}] variable to an object as shown below. 
`<select-searchable
        item-content
        [(ngModel)]="port"
        [items]="ports"
        itemValueField="id"
        itemTextField="name"
        [canSearch]="true"
        (onChange)="portChange($event)">
    </select-searchable>`

`port = {id:1, country: USA}`

**Comment by eakoriakin** [comment]
Hey, great, so problem solved? Or do you need any help?

**Comment by coolvasanth** [comment]
I got solution @eakoriakin. Thanks for your time to reply.

**Comment by eakoriakin** [comment]
Hey, sure, there are such docs here:
https://github.com/eakoriakin/ionic-select-searchable/wiki/Documentation

And a demo as well:
https://stackblitz.com/edit/ionic-select-searchable-initial-value?file=pages%2Fhome%2Fhome.html

And there many other demos that might help you later:
https://stackblitz.com/@eakoriakin

**Comment by eakoriakin** [comment]
And don't forget to star the project here 🙂 
https://github.com/eakoriakin/ionic-select-searchable
