### ISSUE TITLE
Search between two texts

### ISSUE THREAD

**Issue by codecrab-studios** [eakoriakin/ionic-select-searchable-demo#9]
Hi
Thanks for providing an excellent plugin. and is helping me a lot in one my client's project. 

But i have a small query. When we send the data into [items], i have some fields like school_name, school_chinese_name  and we send itemTextField="school_name", and while searching in the next page, its only searching or filtering base don that particular field.

Can i filter data based on both school_name or school_chinese_name?  means if someones types in chinese also in the search bar. i want to search the data based on school_chinese_name field too.

Pl. help!

**Comment by eakoriakin** [comment]
Hello, you can override the default searching by providing your search method to `onSearch` property.
Have a look at the sample below.

Template:
```
<select-searchable
    [(ngModel)]="port"
    title="Port"
    itemValueField="id"
    itemTextField="name"
    [items]="ports"
    [canSearch]="true"
    (onSearch)="searchPorts($event)">
</select-searchable>
```

TypeScript:
```
searchPorts(event: { component: SelectSearchable, text: string }) {
    let text = (event.text || '').trim().toLowerCase();

    // Here we filter an array of ports, that we get from some getPorts() method.
    // Filtering is done by two fields `port.name` and `port.country`.
    event.component.items = this.getPorts().filter(port => {
        return port.name.toLowerCase().indexOf(text) !== -1 ||
            port.country.toLowerCase().indexOf(text) !== -1;
    });
}
```

**Comment by codecrab-studios** [comment]
What is this  this.getPorts()?

**Comment by codecrab-studios** [comment]
<select-searchable
                title="{{'EDIT_PROFILE_SELECT_SCHOOL' | translate}}"
                [(ngModel)]="userData.school_id"
                [items]="schools.data"
                itemValueField="id"
                itemTextField="school_name"
                searchPlaceholder="{{'EDIT_PROFILE_SEARCH_FOR_SCHOOL' | translate}}"
                [canSearch]="true"
                (onChange)="selectSchool($event)"
                (onSearch)="searchPorts($event)">
            </select-searchable>   

I have sent data as Schools.data, and i just did

 getPorts(){
      return this.schools['data'];;
  }

searchPorts(event: { component: SelectSearchable, text: string }) {
        let text = (event.text || '').trim().toLowerCase();
        event.component.items = this.getPorts().filter(port => {
            return port.school_name.toLowerCase().indexOf(text) !== -1 ||
                port.school_chinese_name.toLowerCase().indexOf(text) !== -1;
        });
  }


But when i type some Chinese Character in search bar it doesn't show any result!

**Comment by codecrab-studios** [comment]
Whenver i type anything in the searchbar, and console.log(text).. it always gives Null in searchPorts function

**Comment by codecrab-studios** [comment]
and seems like the Ionic is not able to search Chinese Characters. Do you have any idea about it?

**Comment by eakoriakin** [comment]
Does the search work for you with English letters? I've never had to use Chinese characters though, can you try goggling it? I would expect Ionic to work correctly with any unicode symbols...
